opam-version: "2.0"
version: "0.3.0"
synopsis: "Rocq utilities for proving Gospel using CFML"
description: """\
This package offers an implementation of the Gospel standard library using TLC
and OCaml primitive types using CFML"""
maintainer: "tl.soares@campus.fct.unl.pt"
authors: [
  "Tiago Soares"
]
license: "MIT"
homepage: "https://github.com/ocaml-gospel/gospel"
dev-repo: "git://github.com/ocaml-gospel/gospel"
bug-reports: "https://github.com/ocaml-gospel/gospel/issues"
depends: [
  "dune" {>= "3.19"}
  "coq-tlc"
  "odoc" {with-doc}
]
build: [
  ["dune" "subst"] {dev}
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
    "@doc" {with-doc}
  ]
]
x-maintenance-intent: ["(latest)"]
