(**************************************************************************)
(*                                                                        *)
(*  GOSPEL -- A Specification Language for OCaml                          *)
(*                                                                        *)
(*  Copyright (c) 2018- The VOCaL Project                                 *)
(*                                                                        *)
(*  This software is free software, distributed under the MIT license     *)
(*  (as described in file LICENSE enclosed).                              *)
(**************************************************************************)

(** Positive tests for the definition of axioms. *)

(*@ axiom ax1 : true /\ true *)
(*@ axiom ax2 : true \/ false *)
(*@ axiom ax3 : false \/ true *)
