(**************************************************************************)
(*                                                                        *)
(*  GOSPEL -- A Specification Language for OCaml                          *)
(*                                                                        *)
(*  Copyright (c) 2018- The VOCaL Project                                 *)
(*                                                                        *)
(*  This software is free software, distributed under the MIT license     *)
(*  (as described in file LICENSE enclosed).                              *)
(**************************************************************************)

(** This module contains a typechecker that uses the Inferno library, which
    handles type inference. We first give definitions for program variables and
    types. We then feed these into the [Solver] functor which allows us to solve
    type constraints. *)

module X = Ident
module T = Types
module S = Structure
open Inferno
open Id_uast
open Tast
module Solver = Solver.Make (X) (S) (T)
open Solver
module W = Warnings

(** Deep type for functions *)
let deep_arrow arg ret =
  let f = S.ty_arrow arg ret in
  DeepStructure f

(** [map_binders f xs] is conceptually similar to [List.map], but creates a
    binder for each element in [xs]. This means an application of [f] may bind
    (and possibly return) inferno variables as well as applying some arbitrary
    transformation, as one would expect from [List.map]. This function returns a
    binder that introduces a list of all the values bound by applying [f] to
    every element in [xs]. *)
let rec map_binders (f : 'a -> ('b, 'r) binder) (xs : 'a list) :
    ('b list, 'r) binder =
 fun k ->
  match xs with
  | [] -> k []
  | x :: xs ->
      let@ y = f x in
      let@ l = map_binders f xs in
      k (y :: l)

(** [map_constraints f xs] is conceptually similar to [List.map], but creates a
    constraint for each element in [xs]. The resulting constraint is the
    conjunction of all constraints generated by applying [f] to all the values
    in [xs]. The semantic value of this constraint is a list of the semantic
    values of each constraint created by [f]. *)
let rec map_constraints (f : 'a -> 'b co) (xs : 'a list) : 'b list co =
  match xs with
  | [] -> pure []
  | x :: xs ->
      let+ xs' = map_constraints f xs and+ x' = f x in
      x' :: xs'

let rec map_constraints2 (f : 'a -> 'b -> 'c co) (l1 : 'a list) (l2 : 'b list) :
    'c list co =
  match (l1, l2) with
  | [], [] -> pure []
  | x :: t1, y :: t2 ->
      let+ xs' = map_constraints2 f t1 t2 and+ x' = f x y in
      x' :: xs'
  | _ -> assert false

(* The following functions are used to turn Gospel signatures into Inferno
   constraints that, when solved, will produce typed signatures. If the
   constraint is unsatisfiable, then Inferno will produce an exception which we
   convert into an appropriate Gospel error. *)

(* All Inferno constraints have a semantic value associated with
   them. If a constraint is satisfiable, then Inferno will produce the
   associated sematic value. E.g. the [hastype] function produces a
   constraint whose semantic value is a typed term. This means if
   Inferno can solve the constraint, then it will build a typed
   term. *)

(** [pty_to_deep inferno_vars f t] maps the type [t] to a deep type. Since the
    translation of type variables depends on whether this is the type of a top
    level function or a type annotation for a local variable, this function
    allows the caller to supply an [f] to detail how to handle type variables.
*)
let rec pty_to_deep f pty =
  let pty_to_deep = pty_to_deep f in
  match pty with
  | PTtyvar id -> f id
  | PTtyapp (id, l) -> (
      match id.app_alias with
      | Some t -> pty_to_deep t
      | _ -> DeepStructure (S.Tyapp (id.app_qid, List.map pty_to_deep l)))
  | PTarrow (arg, ret) -> deep_arrow (pty_to_deep arg) (pty_to_deep ret)
  | PTtuple l -> DeepStructure (S.Tytuple (List.map pty_to_deep l))

(** [pty_to_deep_rigid pty] is a refinement of [pty_to_deep] where each type
    variable in [pty] becomes a rigid type variable i.e. this variable cannot be
    unified with any other type. *)
let pty_to_deep_rigid pty =
  deep (pty_to_deep (fun v -> DeepStructure (Tvar v)) pty)

(** [pty_to_deep_flex vars pty] is a refinement of [pty_to_deep] where each type
    variable in [pty] is mapped to the corresponding inferno variable in the
    associative list [vars]. This way, assuming that all the inferno variables
    in [vars] are flexible, the type variables in the resulting deep type can be
    unified with any other type *)
let pty_to_deep_flex vars pty =
  deep (pty_to_deep (fun v -> DeepVar (List.assoc v.id_tag vars)) pty)

(** [assoc_vars vars] returns a binder for a list where every type variable in
    [vars] is associated with a fresh Inferno type variable. *)
let assoc_vars vars =
  let f var k =
    let@ v = exist in
    k (var.Ident.id_tag, v)
  in
  map_binders f vars

(** [record_ty env rfid] returns a binder that introduces the record type that
    the record label [rfid] belongs to as well as the type variables in the
    record type. *)
let record_ty params rid =
 fun k ->
  let@ vars = assoc_vars params in
  let@ ty = shallow (S.Tyapp (Qid rid, List.map snd vars)) in
  k (vars, ty)

(** [field_pty vars q t ty] returns a binder that introduces [q], [t] and an
    inferno type variable whose value is equal to [ty]. *)
let field_pty vars q t ty =
 fun k ->
  let@ ty = pty_to_deep_flex vars ty in
  k (q, t, ty)

(** [top_level_pty env id] returns a binder that introduces the type of the top
    level function [id]. *)
let top_level_pty params ty =
 fun k ->
  (* Associate each type variable in [params] with a flexible inferno
      variable. *)
  let@ vars = assoc_vars params in
  (* Turn the type [ty] into an inferno type variable *)
  let@ ty = pty_to_deep_flex vars ty in
  k (ty, List.map2 (fun x (_, y) -> (x, y)) params vars)

(** [binder_to_deep pty] If [pty] is not [Some t], creates an Inferno variable
    that is equal to [t]. If not, create an unconstrained inferno variable *)
let pty_opt_to_deep = function
  | None ->
      fun k ->
        let@ v = exist in
        let annot = decode v in
        k (v, annot)
  | Some ty ->
      fun k ->
        let@ v = pty_to_deep_rigid ty in
        k (v, pure ty)

(** [ids_of_pat pat] returns a binder for an associative list that maps
    identifier tags with their respective inferno variables. *)
let rec ids_of_pat pat k =
  match pat.Id_uast.pat_desc with
  | Pwild -> k []
  | Pid id ->
      let@ v = exist in
      k [ (id.id_tag, (id, v)) ]
  | Ptuple l ->
      let@ l = map_binders ids_of_pat l in
      k (List.concat l)
  | Pcast (p, _) -> ids_of_pat p k

(** [pat_to_deep ids pat] returns a binder for a pair of an inferno variable for
    a type that matches the pattern and a constraint for the pattern. *)
let rec pat_desc_to_deep ids pat k =
  match pat.Id_uast.pat_desc with
  | Pwild ->
      let@ v, _ = pty_opt_to_deep None in
      k (v, pure Tast.Pwild)
  | Pid id ->
      let _, v = List.assoc id.id_tag ids in
      let pat =
        let+ annot = decode v in
        Pid (mk_ts id annot)
      in
      k (v, pat)
  | Ptuple l ->
      let@ l = map_binders (pat_to_deep ids) l in
      let vl, pl = List.split l in
      let@ v = shallow (S.Tytuple vl) in
      let pat =
        let+ l = map_constraints (fun x -> x) pl in
        Tast.Ptuple l
      in
      k (v, pat)
  | Pcast (p, ty) ->
      let@ v, c = pat_to_deep ids p in
      let loc = pat.pat_loc in
      let c =
        Solver.correlate (loc.loc_start, loc.loc_end)
        @@
        let@ ty_var = pty_to_deep_rigid ty in
        let+ pat = c and+ () = ty_var -- v in
        Pcast (pat, ty)
      in
      k (v, c)

and pat_to_deep ids p =
 fun k ->
  let@ v, c = pat_desc_to_deep ids p in
  let c =
    let+ pat_desc = c in
    { pat_desc; pat_loc = p.pat_loc }
  in
  k (v, c)

(** [build_def vars c] Creates a constraint that adds the variables in [vars] to
    the scope of constraint [c] via a chain of [def] constraints. *)
let build_def vars c =
  List.fold_right
    (fun tid c ->
      let@ ty = pty_to_deep_rigid tid.ts_ty in
      def tid.ts_id ty c)
    vars c

(** [build_def_opt vars c] Returns a constraint where the variables in [l] have
    been added to the scope of constraint [c] by means of a chain of [def]
    constraints.

    Each element of [vars] is a pair consisting of an identifier [x] and its
    type annotation. If [None], then the user did not supply one and we
    associate it with a flexible Inferno type variable.

    The semantic value of the returned constraint is the semantic value of [c]
    coupled with the list of bound variables and their types. This list is
    identical to [vars] except that all [None] values have been replaced with
    the inferred type. *)
let build_def_opt vars c =
  (* [loop (id, ty_annot) c] creates a constraint stating that
     variable [id] has type [ty_annot] in constraint [c]. The semantic
     value of this constraint is the same as [c], except we add the
     variable [id] and coupled with its inferred type to the returned
     list. *)
  let loop (id, ty_annot) c =
    let@ ty_res, annot = pty_opt_to_deep ty_annot in
    let+ annot = annot and+ l, t = def id ty_res c in
    (mk_ts id annot :: l, t)
  in
  (* Map the constraint [c] to one where the semantic value is a pair whose
     first element is an empty list and the second is the semantic value of [c]
     so we can build the list of typed arguments while keeping the previous
     value unchanged. *)
  let acc =
    let+ t = c in
    ([], t)
  in
  List.fold_right loop vars acc

(** [fold_right_binders f l r] is effectively a [List.fold_right] but the
    accumulating function returns a binder. *)
let rec fold_right_binders f l r =
  match l with
  | [] -> fun k -> k r
  | x :: t ->
      fun k ->
        let@ r = fold_right_binders f t r in
        let@ r = f x r in
        k r

(** [hastype ts t r] receives an untyped term [t] and the expected type [r] and
    produces a constraint whose semantic value is a typed term. The environment
    [ts] is used to ensure that all type annotations are valid. *)
let rec hastype (t : Id_uast.term) (r : variable) =
  (* This line ensures that Inferno errors refer to the correct code
     fragment. *)
  Solver.correlate (t.term_loc.loc_start, t.term_loc.loc_end)
  @@
  let+ t_node =
    match t.term_desc with
    | Id_uast.Ttrue ->
        (* For true and false, we state that the expected type is
           bool *)
        let+ () = r --- S.ty_bool in
        Ttrue
    | Tfalse ->
        let+ () = r --- S.ty_bool in
        Tfalse
    | TTrue ->
        (* For True and False (capitalized) we state that the expected
           type is prop *)
        let+ () = r --- S.ty_prop in
        TTrue
    | TFalse ->
        let+ () = r --- S.ty_prop in
        TFalse
    | Tconst constant ->
        (* Depending on the type of constant, we restrict the expected type
            accordingly *)
        let+ () =
          match constant with
          | Pconst_integer _ -> r --- S.ty_integer
          | Pconst_char _ -> r --- S.ty_char
          | Pconst_string _ -> r --- S.ty_string
          | Pconst_float _ -> r --- S.ty_float
        in
        Tconst constant
    | Tlocal id ->
        (* If the variable is defined within the scope of this term,
            we create a constraint stating that the variable [id]
            must be an instance of type [r]. No lookup is performed
            as the bookkeeping is done by Inferno. *)
        let+ _ = instance id r in
        (* We can ignore the return value of [instance] since it will always
            return the empty list since all local variables are bound with
            [def], which creates a monomorphic scheme. *)
        Tvar (Qid id, [])
    | Tvar (q, params, pty) ->
        (* In the case of a top level definition outside the scope of this term,
            we use the type provided during the name resolution stage. *)
        let@ ty, l = top_level_pty params pty in
        let+ () = r -- ty
        and+ ptys =
          map_constraints
            (fun (x, y) ->
              let+ y = decode y in
              (x, y))
            l
        in
        (* If the type of this variable uses any flexible inferno type
           variables that were not unified, then we create an explicit
           application of [q] to the types it receives as argument. *)
        Tvar (q, ptys)
    | Tlet (pat, t1, t2) ->
        (* let id1, id2, ... = t1 in t2 *)
        (* Associative list that maps each identifier in [pat] to an
            inferno variable. *)
        let@ ids = ids_of_pat pat in
        let@ v_type, pat = pat_to_deep ids pat in
        let+ t1 = hastype t1 v_type
        and+ t2 =
          (* Create a constraint for the term [t2] where we add to
              the scope every variable in [ids]. *)
          let t2 = hastype t2 r in
          List.fold_left (fun r (_, (id, v)) -> def id v r) t2 ids
        and+ pat = pat in
        Tlet (pat, t1, t2)
    | Tapply (t1, t2) ->
        (* t1 t2 (Function application)*)
        (* Inferno variables for the function's argument and return type. *)
        let@ arg_ty = exist in
        let@ res = exist in
        (* The term [t1] must be of the function type [arg_ty -> r]. *)
        let+ t1 = lift hastype t1 (S.ty_arrow arg_ty res)
        (* The argument [t2] has some type [arg_ty]. *)
        and+ t2 = hastype t2 arg_ty
        (* The return value of the term has the same type of the return value of
            the function.

            Note: Although [res] could be inlined with [r] with no functional
            difference in terms of typechecking, doing it this way forces Inferno
            to first solve the previous two constraints meaning we will get a more
            precise error message when the return type is invalid. If this is
            unclear, try replacing [res] with [r] and see what happens. *)
        and+ () = r -- res in
        Tapply (t1, t2)
    | Tquant (q, l, t) ->
        (* forall. x y z. t *)
        (* The term [t] must be a formula *)
        let c = lift hastype t S.ty_prop in
        (* Transform the list of Gospel type annotation into a list of
            Inferno binders *)
        let+ l, t = build_def_opt l c in
        Tquant (q, l, t)
    | Tif (g, then_b, else_b) ->
        (* if g then then_b else else_b *)
        (* The guard must have type [bool] *)
        let+ g = lift hastype g S.ty_prop
        (* Both branches must have the return type [r] *)
        and+ then_b = hastype then_b r
        and+ else_b = hastype else_b r in
        Tif (g, then_b, else_b)
    | Tset (v, p) ->
        (* { v | p }*)
        let@ v_var = exist in
        let c = lift hastype p S.ty_prop in
        (* The proposition [p] must have type [prop] *)
        let+ t = def v v_var c
        (* The variable [v] is defined in the constraint [c] *)
        and+ v_ty = decode v_var
        and+ () = r --- S.ty_set v_var in
        (* The return type is a set of [v_ty] where [v_ty] is the
           type of [v] *)
        Tset (mk_ts v v_ty, t)
    | Ttuple l ->
        (* Given a term [t], returns a binder that returns a fresh Inferno
            variable [v] and a constraint stating that the type of the term is
            [v]. *)
        let f t =
         fun k ->
          let@ v = exist in
          k (hastype t v, v)
        in

        (* Creates a constraint and a variable for each term in the tuple *)
        let@ vars = map_binders f l in

        (* Joins all the constraints in [vars] into a single constraint *)
        let+ l = map_constraints fst vars
        (* The return type must be equal to the type of the tuple *)
        and+ () = r --- Tytuple (List.map snd vars) in
        Ttuple l
    | Tlambda (args, t, pty) ->
        (* The return of the function as an inferno variable. *)
        let@ res, annot = pty_opt_to_deep pty in
        (* The types of the function's argument. *)
        let@ ids =
          fold_right_binders
            (fun x acc k ->
              let@ l = ids_of_pat x in
              k (l @ acc))
            args []
        in
        let@ args_ty = map_binders (pat_to_deep ids) args in
        let ptys, pats = List.split args_ty in
        (* The function's type as an inferno variable. *)
        let@ ty_fun =
          fold_right_binders
            (fun v acc -> shallow (S.Tyarrow (v, acc)))
            ptys res
        in
        let c = hastype t res in
        (* Add each variable to the scope of the term. *)
        let+ t = List.fold_right (fun (_, (id, v)) acc -> def id v acc) ids c
        (* Create the list of typed arguments. *)
        and+ pats = map_constraints (fun x -> x) pats
        (* The type of this term is the type of the function. *)
        and+ () = r -- ty_fun
        and+ annot_ty = annot in
        Tlambda (pats, t, Option.map (fun _ -> annot_ty) pty)
    | Trecord (l, rec_ty) ->
        (* Gets the record type as well as the list of type parameters used as
            inferno variables. *)
        let@ vars, r_ty = record_ty rec_ty.params rec_ty.name in
        (* Get the expected type of each record label. *)
        let@ tys = map_binders (fun (q, t, ty) -> field_pty vars q t ty) l in
        (* Associate each field instantiation with its expected type *)
        let check_field (q, t, v) =
          let+ t = hastype t v in
          (q, t)
        in
        let+ l = map_constraints check_field tys and+ () = r -- r_ty in
        Trecord l
    | Tfield (t, rec_ty, field, ty) ->
        (* Get the type for the record which [field] belongs to. *)
        let@ vars, r_ty = record_ty rec_ty.params rec_ty.name in
        (* Get the type of the field. *)
        let@ ty = pty_to_deep_flex vars ty in
        (* The term [t] must be of the type of the record which [t] belongs
            to. Additionally, the type of this term must be equal to the type of
            the field. *)
        let+ t = hastype t r_ty and+ () = r -- ty in
        Tfield (t, field)
    | Tattr (s, t) ->
        let+ t = hastype t r in
        Tattr (s, t)
    | Tcast (t, ty) ->
        (* Turn the type annotation into a deep type. *)
        let@ ty_var = pty_to_deep_rigid ty in
        let+ t = hastype t r
        (* Ensure that the type annotation corresponds with the type of the
            term. *)
        and+ () = r -- ty_var in
        Tcast (t, ty)
    | Tscope (q, t) ->
        (* Since name resolution has already been handled, we can safely ignore
            local scopes. *)
        let+ t = hastype t r in
        Tscope (q, t)
    | Told t ->
        let+ t = hastype t r in
        Told t
  (* By calling [decode], we can get the inferred type of the term. *)
  and+ t_ty = decode r in
  mk_term t_node t_ty t.term_loc

let solve c = Solver.solve ~rectypes:false c

(** Solves an arbitrary constraint assuming types are not allowed to be
    recursive *)
let typecheck tvars c =
  Types.add_tvars tvars;
  try
    let t = snd (solve (let0 c)) in
    let l = Types.clear_tvars () in
    (t, l)
  with
  | Solver.Unify (loc, ty1, ty2) -> Types.incompatible_types loc ty1 ty2
  | Solver.Cycle (loc, pty) -> Types.cycle loc pty
  | Solver.Unbound _ -> assert false
  (* Unbound variables are caught before we run the solver *)
  | Solver.VariableScopeEscape _ -> assert false
(* This exception is only thrown when using rigid Inferno variables. *)

let fmla t =
  let@ ty = shallow S.ty_prop in
  hastype t ty

let int_term t =
  let@ ty = shallow S.ty_integer in
  hastype t ty

let fspec_constraint f =
  let+ pre = map_constraints fmla f.Id_uast.fun_req
  and+ post = map_constraints fmla f.Id_uast.fun_ens
  and+ variant = map_constraints int_term f.fun_variant in
  mk_fun_spec pre post variant f.fun_text f.fun_loc

let invariant_constraint id ty inv =
  let t = fmla inv in
  let@ ty = pty_to_deep_rigid ty in
  def id ty t

(** [function_cstr ts f] Creates a constraint whose semantic value is a list of
    signatures whose head is the declaration of the function described by [f].
    This is the conjunction of two constraints: one that checks if the body of
    the function is well typed and another that checks if the function's
    specification is well typed. *)
let function_cstr (f : Id_uast.function_) : (Tast.function_ * Id_uast.pty) co =
  (* Turn the return type into a deep type *)
  let ret_pty = Option.value ~default:Constants.ty_prop f.fun_type in
  let arrow_ty =
    List.fold_right
      (fun (_, pty) acc -> PTarrow (pty, acc))
      f.fun_params ret_pty
  in

  let@ ret_ty = pty_to_deep_rigid ret_pty in

  (* The function type encoded as a deep type *)
  let@ fun_ty = pty_to_deep_rigid arrow_ty in

  (* Typecheck the body of the function. Must have the same return
     type that the user indicated. *)
  let body_c =
    match f.fun_def with
    | None -> pure None
    | Some t ->
        let c = hastype t ret_ty in
        let+ tt =
          if f.fun_rec then
            (* If the function is recursive, it must be defined within
               the scope of the term. *)
            def f.fun_name fun_ty c
          else c
        in
        Some tt
  in
  (* Combines the constraint for the function body and the constraint for the
     specification. This way, they can be solved under the same chain of [def]
     constraints. *)
  let fco =
    let+ body = body_c and+ spec = fspec_constraint f.fun_spec in
    (body, spec)
  in

  (* Function parameters, typed term and typed function specification. *)
  let params = List.map (fun (x, t) -> mk_ts x t) f.fun_params in
  let+ tt, fun_spec = build_def params fco in
  let f = mk_function f params tt ret_pty fun_spec in
  (f, arrow_ty)

(** Creates a constraint ensuring the term within an axiom has type [prop]. *)
let axiom_cstr ax =
  let+ t = fmla ax.Id_uast.ax_term in
  mk_axiom ax.ax_name t ax.ax_loc ax.ax_text

(** Checks if a lens of kind [provided] lens can be used when we expected a lens
    of kind [expected]. *)
let match_lens_kind ~loc expected provided =
  match (expected, provided) with
  | Persistent, Persistent -> ()
  | Mutable, _ -> ()
  | _ -> W.error ~loc W.Expected_persistent_lens

let rec match_lenses ~loc tovars tgvars (expected, provided) =
  let open Uast_utils in
  match provided with
  | Lidapp app ->
      match_lens_kind ~loc expected.lkind app.lapp_kind;
      let@ provided_ocaml = pty_to_deep_rigid app.lapp_ocaml in
      let@ expected_ocaml = pty_to_deep_flex tovars expected.locaml in
      let@ provided_model = pty_to_deep_rigid app.lapp_model in
      let@ expected_model = pty_to_deep_flex tgvars expected.lmodel in
      let+ () = provided_ocaml -- expected_ocaml
      and+ () = provided_model -- expected_model
      and+ _ =
        map_constraints
          (match_lenses ~loc tovars tgvars)
          (List.combine app.lapp_expected_params app.lapp_params)
      in
      ()
  | _ -> assert false

let pty_lens_cstr ~loc v ocaml_ty app =
  let lovars = Uast_utils.pty_tvars app.lapp_ocaml in
  let lgvars = Uast_utils.pty_tvars app.lapp_model in
  let@ tovars = assoc_vars lovars in
  let@ expected = pty_to_deep_flex tovars app.lapp_ocaml in
  let@ provided = pty_to_deep_rigid ocaml_ty in
  let@ tgvars = assoc_vars lgvars in
  let@ model = pty_to_deep_flex tgvars app.lapp_model in
  let lens_params = List.combine app.lapp_expected_params app.lapp_params in
  let+ _ = map_constraints (match_lenses ~loc tovars tgvars) lens_params
  and+ () = expected -- provided
  and+ () = model -- v
  and+ t = decode model in
  t

let rec lens_to_app l =
  let lens_to_app = fun x -> Lidapp (lens_to_app x) in
  match l with
  | Lidapp app ->
      { app with lapp_params = List.map lens_to_app app.lapp_params }
  | Lvar id ->
      let eid = Qid (Ident.mk_id ~loc:id.Ident.id_loc "Encode") in
      Uast_utils.mk_lens_app eid Persistent (PTtyvar id) (PTtyvar id) [] []
  | Ltuple l ->
      let n = List.length l in
      let id = Qid (Ident.mk_id ("Tuple" ^ string_of_int n)) in
      let tvars = List.init n (fun x -> Ident.mk_id ("a" ^ string_of_int x)) in
      let ty = PTtuple (List.map (fun t -> PTtyvar t) tvars) in
      let expected_params =
        List.map
          (fun v ->
            Uast_utils.mk_lens_info (Ident.mk_id "H") Mutable (PTtyvar v) []
              (PTtyvar v))
          tvars
      in
      Uast_utils.mk_lens_app id Persistent ty ty expected_params
        (List.map lens_to_app l)
  | Larrow (l1, l2) ->
      let id = Qid (Ident.mk_id "Arrow") in
      let tvar1 = PTtyvar (Ident.mk_id "A") in
      let tvar2 = PTtyvar (Ident.mk_id "B") in
      let ty = PTarrow (tvar1, tvar2) in
      let expected_params =
        [
          Uast_utils.mk_lens_info (Ident.mk_id "A") Mutable tvar1 [] tvar1;
          Uast_utils.mk_lens_info (Ident.mk_id "B") Mutable tvar2 [] tvar2;
        ]
      in
      Uast_utils.mk_lens_app id Persistent ty ty expected_params
        [ lens_to_app l1; lens_to_app l2 ]

let apply_lens nm ocaml_ty lens =
  Solver.correlate (lens.lens_loc.loc_start, lens.lens_loc.loc_end)
  @@
  let lens_app = lens_to_app lens.lens_desc in
  pty_lens_cstr ~loc:lens.lens_loc nm ocaml_ty lens_app

let sp_ocaml_var_apply_lens (model, model') v =
  let+ pre_pty = apply_lens model v.Id_uast.ty_ocaml v.ty_gospel_cons
  and+ post_pty = apply_lens model' v.ty_ocaml v.ty_gospel_prod in
  {
    var_name = v.var_name;
    ty_ocaml = v.ty_ocaml;
    ty_gospel_cons = (pre_pty, v.ty_gospel_cons);
    ty_gospel_prod = (post_pty, v.ty_gospel_prod);
    ro = v.ro;
  }

(** [sp_var_lens arg] in the case of OCaml values applies the corresponding
    lenses and obtains the model of the variable in the pre and post condition.
    In the cases where this is not an OCaml variable, this function creates an
    "{
          identity" constraint *)
let sp_var_apply_lens modelv s =
  match s with
  | Id_uast.Unit -> pure Unit
  | Wildcard -> pure Wildcard
  | Ghost (id, pty) ->
      let model, _ = modelv in
      let@ v = pty_to_deep_rigid pty in
      let+ () = model -- v in
      Ghost (id, pty)
  | OCaml v ->
      let+ v = sp_ocaml_var_apply_lens modelv v in
      OCaml v

let sp_ocaml_var_to_tvar acc (model, model') v =
  let id = Uast_utils.leaf v.Id_uast.var_name in
  let pre_id = id in
  let post_id = Ident.mk_updated id in
  def pre_id model (def post_id model' acc)

(** [sp_var arg] turns a value of type [sp_var] into either 0, 1 or 2 [tsymbol]s
    depending on the argument. *)
let sp_var_to_tvar acc modelv s =
  match s with
  | Id_uast.Unit | Wildcard -> acc
  | Ghost (v, pty) ->
      let model, _ = modelv in
      def v model acc
  | OCaml v -> sp_ocaml_var_to_tvar acc modelv v

let xspec (spec : Id_uast.xpost_spec) =
  let f =
   fun _ k ->
    let@ v1 = exist in
    let@ v2 = exist in
    k (v1, v2)
  in
  let@ argsv = map_binders f spec.sp_xargs in
  let@ retsv = map_binders f spec.sp_xrets in
  let@ tops = map_binders f spec.sp_xtops in

  let+ args = map_constraints2 sp_var_apply_lens argsv spec.sp_xargs
  and+ rets = map_constraints2 sp_var_apply_lens retsv spec.sp_xrets
  and+ topsv = map_constraints2 sp_ocaml_var_apply_lens tops spec.sp_xtops
  and+ xpost =
    let xpost = map_constraints fmla spec.sp_xpost in
    let xpost = List.fold_left2 sp_var_to_tvar xpost argsv spec.sp_xargs in
    let xpost = List.fold_left2 sp_var_to_tvar xpost retsv spec.sp_xrets in
    List.fold_left2 sp_ocaml_var_to_tvar xpost tops spec.sp_xtops
  in

  mk_xpost spec.sp_exn args rets topsv xpost spec.sp_xloc

(** Creates a constraint ensuring that the terms within [pre] and [post] are
    well typed. *)
let spec_cstr (spec : Id_uast.val_spec) =
  (* Constraint that solves each pre and post condition. *)
  let f =
   fun _ k ->
    let@ v1 = exist in
    let@ v2 = exist in
    k (v1, v2)
  in
  let@ argsv = map_binders f spec.sp_args in
  let@ retsv = map_binders f spec.sp_rets in
  let@ topsv = map_binders f spec.sp_tops in

  let+ args = map_constraints2 sp_var_apply_lens argsv spec.sp_args
  and+ rets = map_constraints2 sp_var_apply_lens retsv spec.sp_rets
  and+ tops = map_constraints2 sp_ocaml_var_apply_lens topsv spec.sp_tops
  and+ pre, post, xspec, checks =
    let fmlas =
      let+ pre = map_constraints fmla spec.sp_pre
      and+ post = map_constraints fmla spec.sp_post
      and+ xspec = map_constraints xspec spec.sp_xpost
      and+ checks = map_constraints fmla spec.sp_checks in
      (pre, post, xspec, checks)
    in
    let fmlas = List.fold_left2 sp_var_to_tvar fmlas argsv spec.sp_args in
    let fmlas = List.fold_left2 sp_var_to_tvar fmlas retsv spec.sp_rets in
    List.fold_left2 sp_ocaml_var_to_tvar fmlas topsv spec.sp_tops
  in
  mk_vspec args rets tops pre checks post xspec spec.sp_diverge spec.sp_pure
    spec.sp_text spec.sp_loc

let axiom tvars ax =
  let ax, vars = typecheck tvars (axiom_cstr ax) in
  { ax with ax_tvars = tvars @ vars }

let function_ tvars f =
  let (f, pty), vars = typecheck tvars (function_cstr f) in
  ({ f with fun_tvars = tvars @ vars }, pty)

let spec tvars spec =
  let spec, vars = typecheck tvars (spec_cstr spec) in
  (spec, vars)

let invariant tvars id ty inv =
  (* TODO: What to do about type variables defined in type invariants. *)
  let t, _ = typecheck tvars (invariant_constraint id ty inv) in
  t

let ty_inst ty tvars args =
  let c =
    let@ vars = assoc_vars tvars in
    let@ t = pty_to_deep_flex vars ty in
    let combine = List.combine vars args in
    let+ _ =
      map_constraints
        (fun ((_, v1), ty) ->
          let@ v2 = pty_to_deep_rigid ty in
          v1 -- v2)
        combine
    and+ t = decode t in
    t
  in
  (* This call to solve can never fail for any valid function call. *)
  let _, t = solve (let0 c) in
  t

let apply_lens t lens =
  fst
    (typecheck []
       (let@ v = exist in
        apply_lens v t lens))
